### PR TITLE
Snomed ct script update

### PR DESCRIPTION
**Pull request by amwarnock**
# Description
We have a new template to help streamline the ADS data collection process. This PR updates the SNOMED CT UMLS single pull script to ingest the new template and output a well formatted excel sheet.

## What was the problem?
The old python script was outdated.

## How does this fix it?
This updates the UMLS script to easily ingest the new template format and output an excel file with the following columns:

- VASRD Code
- Data Concept
- CFR Criteria
- Code Set
- Code
- Code Description
- Keyword

## Jira Tickets
MCP-XXXX

## How to test this PR
Run the script, using the new template.

### CODE REVIEW

**Comment by amwarnock** [comment]
Note to self: This currently does not filter the data type.  It will see if there is a SNOMED CT code for all Keywords involved in the ingested keywords sheet.  After you get more information about SNOMED CT data pulls, update this accordingly and then request review.

**Comment by amwarnock** [comment]
Update: Script will consider all keywords except medications

**Review by jlpeterson2 — APPROVED** [review]
Great work, thanks!

**Review by ZubairL — APPROVED** [review]
currently running on skin keywords, crossing my fingers that it doesn't crash

**Comment by amwarnock** [comment]
> currently running on skin keywords, crossing my fingers that it doesn't crash

Thanks Zubair! I'll wait to see how it works for skin before merging.  As a heads up, it took at least 30-45 minutes to run for Scars - so I expect it to take a while to run for Skin. I expect it to run a lot faster for conditions with less keywords.

**Pull request merged**
